description: "MNIST D-SGD with fully connected topology and high non-IID data"

network:
  package: "p2pfl.communication.protocols.protobuff.memory"
  protocol: "MemoryCommunicationProtocol"
  nodes: 10
  topology: "full"

experiment:
  name: "mnist_fully_dsgd"
  rounds: 100
  epochs: 1
  trainset_size: 10
  seed: 666
  wait_timeout: 300

  dataset:
    source: "huggingface"
    name: "p2pfl/MNIST"
    batch_size: 128
    partitioning:
      package: "p2pfl.learning.dataset.partition_strategies"
      strategy: "DirichletPartitionStrategy"
      reduced_dataset: false
      reduction_factor: 10
      params:
        alpha: 0.1

  model:
    package: "p2pfl.examples.mnist.model.mlp_pytorch"
    model_build_fn: "model_build_fn"
    params:
      lr_rate: 0.1

  aggregator:
    package: "p2pfl.learning.aggregators.d_sgd"
    aggregator: "DSGD"
    params: {}

settings:
  general:
    log_level: "INFO"
    grpc_timeout: 60
    disable_ray: false
    resource_monitor_period: 10

  SSL:
    use_ssl: false

  heartbeat:
    period: 10
    timeout: 300
    wait_convergence: 10
    exclude_beat_logs: true

  gossip:
    period: 1
    ttl: 20
    messages_per_period: 9999999
    amount_last_messages_saved: 1000
    models_period: 0.5
    models_per_round: 10
    exit_on_x_equal_rounds: 5

  training:
    vote_timeout: 60
    aggregation_timeout: 1200
    ray_actor_pool_size: 10
    neighbor_only_aggregation: true

profiling:
  enabled: false
  measure_time: true
  output_dir: "profile/mnist_fully_dsgd"
